# This file is part of CODEPLOY.ORG.
#
# CODEPLOY.ORG is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# CODEPLOY.ORG is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with CODEPLOY.ORG. If not, see <https://www.gnu.org/licenses/>. 

# Environment specific
- name : Finding 'initialize' items in 'environment'
  shell: ls -v ./roles/initialize/tasks/environment
  register: items

- name : Looping the sorted 'initialize' items in 'environment'
  include_tasks: ./roles/initialize/tasks/environment/{{ item }}
  loop: "{{ items.stdout_lines}}"

# Hardware specific
- name : Finding 'initialize' items in 'hardware'
  shell: ls -v ./roles/initialize/tasks/hardware
  register: items

- name : Looping the sorted 'initialize' items in 'hardware'
  include_tasks: ./roles/initialize/tasks/hardware/{{ item }}
  loop: "{{ items.stdout_lines}}"

# Operating System specific
- name : Finding 'initialize' items in 'os'
  shell: ls -v ./roles/initialize/tasks/os
  register: items

- name : Looping the sorted 'initialize' items in 'os'
  include_tasks: ./roles/initialize/tasks/os/{{ item }}
  loop: "{{ items.stdout_lines}}"
