# This file is part of CODEPLOY.ORG.
#
# CODEPLOY.ORG is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# CODEPLOY.ORG is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with CODEPLOY.ORG. If not, see <https://www.gnu.org/licenses/>. 
- name: Create 8GB swap file
  command: dd if=/dev/zero of=/swapfile bs=1024k count=8192
           creates="/swapfile"
  tags:
    - swap.file.create

- name: Change swap file permissions
  file: path="/swapfile"
        owner=root
        group=root
        mode=0600
  tags:
    - swap.file.permissions

- name: "Check swap file type"
  command: file /swapfile
  register: swapfile
  tags:
    - swap.file.mkswap

- name: Make swap file
  command: "sudo mkswap /swapfile"
  when: |
    swapfile.stdout.find('swap file') == -1
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  mount: name=none
         src=/swapfile
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - swap.fstab

- name: Mount swap
  command: "swapon /swapfile"
  when: |
    ansible_swaptotal_mb < 1
  tags:
    - swap.file.swapon
