# This file is part of CODEPLOY.ORG.
#
# CODEPLOY.ORG is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# CODEPLOY.ORG is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with CODEPLOY.ORG. If not, see <https://www.gnu.org/licenses/>. 
---
- name: github-desktop - prerequisites - flatpak
  ansible.builtin.apt:
    pkg:
      - flatpak
      - gnome-software-plugin-flatpak
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: github-desktop - prerequisites - add flatpak repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: github-desktop - deploy
  community.general.flatpak:
    name: io.github.shiftey.Desktop
    state: present
    remote: flathub
